--- 
services: 
  db: 
    build: 
      context: .
      dockerfile: database.Dockerfile
    networks:
      - global
    ports: 
      - "3306:3306"
  serv: 
    depends_on: 
      - db
    build: 
      context: .
      dockerfile: backend.Dockerfile
    networks:
      - global
    ports: 
      - "4001:4001"
    restart: always
networks:
  global:
    name: global